gem 'slim-rails'
gem 'mysql2'
gem 'jwt'
gem 'sinatra', github: "sinatra/sinatra", branch: "2.2.0-alpha"
gem 'sidekiq', '~> 4.0.0',  require: ['sidekiq', 'sidekiq/web']
gem 'bootstrap-sass', '~> 3.3.6'
gem 'simple_form'

gem_group :development, :test do
    gem 'terminal-notifier'
    gem 'terminal-notifier-guard', '~> 1.6.1'
    gem 'byebug'
    gem 'spring'
    gem 'airborne'
    gem 'faker'
    gem 'guard'
    gem 'rspec-rails', '~> 3.0'
    gem 'factory_girl_rails'
    gem 'guard-rspec'
    gem 'spring-commands-rspec'
    gem 'guard-livereload', '~> 2.4', require: false
    gem "rack-livereload"
end

gem_group :development do
    gem 'mina'
    gem 'mina-scp', require: false
    gem 'mina-sidekiq', require: false
end

gem "mini_magick"
gem 'active_model_serializers', '~> 0.10.0.rc2'

gem 'oj'
gem 'oj_mimic_json'

run "bundle install"

file '.gitignore', <<-CODE
# If you find yourself ignoring temporary files generated by your text editor
# or operating system, you probably want to add a global ignore instead:
#   git config --global core.excludesfile '~/.gitignore_global'

# Ignore bundler config.
/.bundle

# Ignore the default SQLite database.
/db/*.sqlite3
/db/*.sqlite3-journal

# Ignore all logfiles and tempfiles.
\.*
/log/*
/tmp/*
/tmp
/log
!/log/.keep
!/tmp/.keep
socket_server.rb
.tags
.tags_sorted_by_file
.idea/
.idea/*
Gemfile.lock
*.sublime-project
*.sublime-workspace
config/pem
config/initializers/yd_init.rb
config/server_config.rb
config/deploy.rb
CODE

file 'app/assets/stylesheets/1st_load_framework.css.scss', <<-CODE
// import the CSS framework
@import "bootstrap-sprockets";
@import "bootstrap";

// make all images responsive by default
img {
  @extend .img-responsive;
  margin: 0 auto;
  }
// override for the 'Home' navigation link
.navbar-brand {
  font-size: inherit;
  }

// THESE ARE EXAMPLES YOU CAN MODIFY
// create your own classes
// to make views framework-neutral
.column {
  @extend .col-md-6;
  @extend .text-center;
  }"
.form {
  @extend .col-md-6;
  }
.form-centered {
  @extend .col-md-6;
  @extend .text-center;
  }
.submit {
  @extend .btn;
  @extend .btn-primary;
  @extend .btn-lg;
  }
// apply styles to HTML elements
// to make views framework-neutral
main {
  @extend .container;
  background-color: #eee;
  padding-bottom: 80px;
  width: 100%;
  margin-top: 51px; // accommodate the navbar
  }
section {
  @extend .row;
  margin-top: 20px;
  }
CODE

file 'app/assets/javascripts/application.js', <<-CODE
// This is a manifest file that'll be compiled into application.js, which will include all the files
// listed below.
//
// Any JavaScript/Coffee file within this directory, lib/assets/javascripts, vendor/assets/javascripts,
// or vendor/assets/javascripts of plugins, if any, can be referenced here using a relative path.
//
// It's not advisable to add code directly here, but if you do, it'll appear at the bottom of the
// compiled file.
//
// Read Sprockets README (https://github.com/sstephenson/sprockets#sprockets-directives) for details
// about supported directives.
//
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require bootstrap-sprockets
//= require_tree .
CODE

run "bundle exec rails g rspec:install"
run "bundle exec rails g simple_form:install --bootstrap"
run "mv app/assets/stylesheets/application.css app/assets/stylesheets/application.css.scss"
run "bundle exec guard init"

after_bundle do
  git :init
  git add: "."
  git commit: %Q{ -m 'Initial commit' }
end
